- CHANGELOG
- filters.txt
Kozmeticky filter pre otravne linky v programe na tv-program.sk
> inline linky na tv-program.sk

- filters.txt
https://easylist-czech-and-slovak.tenderapp.com/help/discussions/problmy/81-titulkycom
> Fixed titulky.com anti-adblock on column with newest titles

- filters.txt
Tohle se zbaví prázdného místa nahoře v cztorrentu
> cztorrent banner

- filters.txt
> Pravidlo pro skrytí Anti-AB dialogu na IDnes

- filters.txt
Ukazka: http://www.hcmotor.cz/index.asp
> Pridani blokace mygivt toolbaru

- filters.txt
1) Web se snazi zpetne prepsat viditelnost u iframu, coz resi pravidlo s `#?#` separatorem.
2) Pridany URL nove nalezenych banneru.
> Aktualizace pro novinky.cz

- filters.txt
> topserialy.to - popup reklama nad play buttonem

- filters.txt
> Reklamni spoty pred videem na novinky.cz

- filters.txt
> Odstraneni reklamy v hlavicce podstranky video.aktualne.cz/dvtv

- filters.txt
> Odstraneni problemoveho pravidla na aktualne.cz

- filters.txt
csfd - horni reklama a leva strana
jen nevim jak se zbavit probliknuti reklamy. Na chvili se ukaze.
> csfd - horni reklama a leva strana

- filters.txt
Also added some generic rules found there and used somewhere else
> Updated navratdoreality.cz

- filters.txt
Removing intrusive (preventing to view the page) adblock removal dialog
> Filter letstrololol.cz adblock warning

- filters.txt
- filters_ublock.txt
Hihinky: AdBlock alert po vzore letstrololol.cz
PC Revue: reklama v hornom banneri a po stranach; reklama v blogu medzi prispevkami
Pocasie.pozri.sk: vyhodenie out-of-date pocasie.pozri.sk/nba2.gif
> hihinky.cz, pcrevue.sk, pocasie.pozri.sk

- filters.txt
- filters_ublock.txt
Blocks loading of video advertisments on tv.idnes.cz
> tv.idnes.cz - videoreklama

- filters_ublock.txt
[Before ](https://i.imgur.com/ia7sgnJ.png) and [after](https://i.imgur.com/3ib4dDr.png)
> Fix csfd.cz video position when surrounded with ad

- filters.txt
Nová reklama se objevila na pravé straně.
> cztorrent (bnr_skyscraper_right)

- filters.txt
Text ads on https://search.seznam.cz/?q=iphone
> Remove search ads on search.seznam.cz

- filters.txt
Removes some non resolving or expired domains
> Remove non resolving domains

- filters.txt
Zbaví se reklamních bannerů na horní části stránky
> e-mostecko reklamy

- filters.txt
> Added rules for ta3.com

- filters.txt
Odstrania sa tym "klikacie pasce" na sector.sk
> Added rules for sector.sk

- filters.txt
whitelist par grafickych prvku na games.cz
@@https://games.tiscali.cz/img/bg/....
> Update filters.txt - games.cz whitelist sprite

- filters.txt
> Added rules for rtvs.sk

- filters.txt
Delete some dead domains, assets and some non czech/slovak rules already blocked by default easylist rules.
> Filters cleanup

- filters.txt
> Added rules for zoznam.sk

- filters.txt
Smazáno `zive.cz,mobilmania.cz,autorevue.cz,e15.cz,maminka.cz,ahaonline.cz,zeny.cz#?#DIV:-abp-has(>A[target="_blank"])`
Kompletně to zničí galerie:
Fotky nejsou videt, ale reklama tam je stale.
https://www.mobilmania.cz/clanky/nejlepsi-chytre-hodinky/sc-3-a-1343375/default.aspx#part=1
https://www.zive.cz/clanky/sapphire-gearbox-bedynka-pro-vykonnou-externi-grafiku-kterou-staci-zapojit-do-usb-c/sc-3-a-196199/default.aspx
> zive,mobilmania... target _blank nici galerie

- filters.txt
> centrum.cz - reklama-leader a obchazeni adblocku

- filters.txt
Zatim se mi nedari nejak spolehlive odstranit celostrankove reklamy.
> Odstrani vetsinu reklam na centrum.cz

- filters.txt
nektere reklamy tam target="_blank" nemaji...
zkoumam i moznosti jak to zablokovat rovnou sitove
> Opet reklamy v pravo

- filters.txt
jako user-filter funguje na 100%, ale z easylistu se chova nejak divne a vetsinou nic nedela. Jen pokus s posunem o par radku vys.
> centrum.cz#$#abort-on-property-read sasia

- filters.txt
Reklamni system nenastavi promenne obsahujici reklamni html a nevyda se pak zadna dalsi reklama.
> centrum.cz#$#abort-on-property-write b1

- filters.txt
hvezdicka z toho dela nepovinne znaky
> www.mobilmania.cz, www.zive.cz: blokovalo vsechna url obrazku obsahujicich pismeno 'x'

- filters_ublock.txt
Another fix of #252 (all non-paid non-organic results should be visible now)
> Fix hidden hints

- filters.txt
Ahoj, pomaham klientovi s vyvojem webu performax.cz a rad bych, aby se mu nacital javascript (bez nej ten web vunec nefunguje). Muzete mi prosim schvalit tuhle zmenu filtru, ktera by mela jenom zajistit, ze se skripty z performaxu.cz budou nacitat POUZE na domene performax.cz? Diky :)
> Neblokovat performax skripty na domene performax.cz

- filters.txt
Odstráni banerovú reklamu v pozadí stranky mtbiker.sk
> Added rules for mtbiker.sk

- filters.txt
Proof:
| Filter | Before | After |
| ----- | -------- | ----- |
| `login.szn.cz###ad` | ![seznam1](https://user-images.githubusercontent.com/53856821/112800485-ffa97f80-906f-11eb-882b-920c3d5d2a47.png) | ![seznam2](https://user-images.githubusercontent.com/53856821/112800490-00421600-9070-11eb-934f-ced78cbb4d34.png) |
| `\|\|vascak.cz/data/img/adblock.png$image` | ![vascak1](https://user-images.githubusercontent.com/53856821/112800491-00daac80-9070-11eb-92fb-5b8c569304c6.png) | ![vascak2](https://user-images.githubusercontent.com/53856821/112800497-020bd980-9070-11eb-91b2-e083f7e3bafc.png) |
> Seznam login, vascak.cz

- filters.txt
> A: unblocked ads on zoznam.sk

- filters.txt
Zablokuje tento reklamny popup ktory sa zobrazi nad prehravacom pri prehravani epizod:
> Serialy.io

- filters.txt
Hi @tomasko126, I would really appreciate if you can review and add the following filters to the list as I got a complain from an ABP user towards this domain `https://www.seznam.cz/`. So I wrote the following filters: 
`seznam.cz##div[data-dot*="gadgetCommercial"]` --to hide this banner top, right side
`seznam.cz##.gadget--zbozi` -- to hide middle row of products advertised 
`seznam.cz##div[style*="max-height:"]` -- to hide the banner with ads
Thanks a lot in advance 🤗
> A: `https://www.seznam.cz/`

- filters.txt
Proof:
|Filter|Before|After|
|---|---|---|
|`\|\|sbazar.cz/*/v1/xhr`|![sbazar_before](https://user-images.githubusercontent.com/53856821/216139879-c7352287-119d-44bf-83a7-8c7f8829844a.png)|![sbazar_after](https://user-images.githubusercontent.com/53856821/216139933-37824638-0c11-4065-848a-130f5b9000f4.png)|
|`www.parabola.cz#@#.rklm`|![parabola_before](https://user-images.githubusercontent.com/53856821/216140001-946a775b-079e-4f3b-84b7-790cdc820324.png)|![parabola_after](https://user-images.githubusercontent.com/53856821/216140033-4d59aae0-5816-41bc-a145-11a218aa2c68.png)|
**Note about sbazar.cz:** Clearing cookies, as well as using incognito mode, didn't work for me, especially on Chromium-based browsers. I found an XHR request which didn't break the page and is primarily related to ads.
> Sbazar.cz, parabola.cz

- filters.txt
Hi 👋 @tomasko126 could you please add this filter to block the ads on `ireceptar.cz` on the side:  
Thanks ☺️
> A: `ireceptar.cz`

- filters_ublock.txt
Using `visibility: hidden` for this one since removing the element messes up the `absolute` `position` of the banner.
> Add another filter for ads on "vranovske.sk"

- filters.txt
This removes a script which blocks actions like viewing the source or right clicking.
> Block anti-theft-system on funnyburger.sk

- filters.txt
> Remove (empty) ad banners on sme.sk

- filters.txt
They have new version of website which adds div elements of advertisement.
> fixed filter for databazeknih.cz

- filters.txt
Odstráni banerovú reklamu na webe radia.sk
> Remove ads on radia.sk

- filters.txt
> General element hide

- filters_ublock.txt
all given under issue report https://github.com/uBlockOrigin/uAssets/issues/23471
antiadblock at `https://tvnoviny.sk/archiv/91-televizne-noviny/183713-23-4-2024` 
using chrome with ublock origin stable
> address https://github.com/uBlockOrigin/uAssets/issues/23471

- filters.txt
Extends my previous PR #382 by adding a similar filter for `https://www.sauto.cz/` website.
> Add `https://www.sauto.cz/`

- filters.txt
Updated filters to bypass adblock detection again.
Funny note - the website owner marked for a short perion all users as adblock users today while updating adblock detection :D
you should see `Good user!` printed in the console
- chrome + manifest v2 ublock origin
- enabled filter lists:
- ublock built-in / all
- ads / easylist (required to block top ad)
- privacy / easyprivacy (required to block sidebar ad)
```
> fix titulky.com v3

- filters.txt
fixes "incorrect configuration" reported at [this source](https://www.titulky.com/?film=1&Prispevek=1619895):
> Aktuální konfigurace blokátoru reklam způsobuje chybné zobrazení webu a vyhledávací blok titulků nezobrazuje vůbec. Tento problém je způsobený neodbornou konfiguraví doplňku, ne ze strany titulky.com
(they added `.pagefoot` to the search`)
> fix titulky.com v6

- filters.txt
- filters_ublock.txt
the site owner updated his anti-adblock 30 minutes ago, so here are the updated filters as usual :)
> fix titulky.com v8

- filters.txt
- filters_ublock.txt
The site owner was bored and has prepared more challenges for me 🥰. Fixed as usual ;)
This code has been online for 4 hours - if you look closely, `if(objadb){` always evaluated to `false` - showing anti-adblock popup even for non-adblock users. Testing in production :D
```js
document.addEventListener("DOMContentLoaded", function() {
if (typeof sssp !== 'object') {
window.errSZ=Date.now();
console.log('Error ssp.js');	    
} else {
console.log('OK ssp.js');
}
});
const objadb2 = document.getElementById('martevax2');
if(objadb){
const objadbstyle = window.getComputedStyle(objadb);
if (objadbstyle.display === 'none') {} else {
var showBanner600=true;
var showBanner700=true;
var showBanner735=true;
var showFairUser=true;
var showFairUser001=true;
bannerSkyscraperHeight='600px'; …
```
> fix titulky.com v9

- filters.txt
> fix titulky.com v12

- filters.txt
Added more filters to block sidebar ads on the homepage. The old filters are still up-to-date
> fix kladenskelisty.cz

- filters.txt
- filters_ublock.txt
Defuses anti-adblock message "Je aktivovaný AdBlock nebo jiný blokátor reklam! Pokud chcete náš web používat, vypněte ho prosím. Děkujeme!".
Also removed unused filter
> fix ewrc.cz

- filters.txt
mrk.cz - added filters to block these first party ads:
- background ad on desktop,
- 2x right sidebar ads
The old filters were bypassed, so I removed them (the ads were moved to /images/ok/)
> fix mrk.cz

- filters.txt
Fixes first party ads for parabola.cz - all filters can be tested on the home page:
- top of the page near the logo
- in the left sidepanel
- in the right sidepanel
- sponsored links in the footer
also removed old unused filters
> fix parabola.cz

- filters.txt
Cosmetic filter to remove empty space after ads were removed. Also removed old filter
> fix moda.cz

- filters.txt
- filters_ublock.txt
Hides top navbar+right sidebar ads + defuses antiadblock.
> fix zdopravy.cz

- filters.txt
- filters_ublock.txt
- Fixed total breakage (with cz+sk filterlist enabled)
- Removed antiadblock (visible if you disable cz+sk filterlist)
- Added cosmetic filter to remove blank space
> fix playzone.cz

- filters_ublock.txt
The site doesn't serve ads anymore
> remove uloz.to

- filters.txt
- filters_ublock.txt
Cosmetic filter to hide blank space (top of the page) from all mediak sites. Also removed old filters, looks like it is handled by other filterlists
> fix mediak

- filters.txt
Removed old filters for these sites:
esemes.cz - forbidden
libise.eu - domain available for sale page
mall.tv - redirect
mladypodnikatel.cz - redirect
serialycz.cz - domain expired
war4all.com - redirect
warforum.cz - redirect
najserialy.to - redirect
serialy.io - domain expired
tvtv.sk - redirect
kniha.cz - redirect
> remove old sites

- filters_ublock.txt
The navbar is pushed out of the page for adblock users. Re-adding filter to fix it
> fix titulky.com v23

- filters.txt
hidden new ads (all of them can be tested on the homepage)
> fix mrk.cz v2
