filters.txt
Website advantage.kentico.com does not contain any ads and fails to load design assets when filter is applied.
=> Enables content from advantage.kentico.com

filters.txt
Zneaktivňuje AdBlock Notify plugin, který po načtení překryje celou stránku a znemožní tak její použití. S touto úpravou se nezobrazují žádné reklamy ani anti-adblock hlášení.
=> Remove anti-adblock from skrblik.cz

filters.txt
S předchozím filtrem vyskakovala chyba ohledně zapnutého adblocku, nyní jsou opět vidět odpovědi bez reklam. 
První pravidlo ošetřuje kontrolu přes FuckAdBlock
Druhé pravidlo ošetřuje ads.js, který obsahuje pouze definici proměnné k ověření, zda jsou reklamy skutečně povolené.
=> Fix anti-adblock for poradte.cz

filters.txt
Nevim proc, ale pravidlo `novinky.cz##script:inject(abort-on-property-write.js, AdBlockTest)` u me zpusobuje, ze nefunguji vsechna ostatni pravidla. Nefunguji pak ani uzivatelska pravidla pro novinky.cz. Testovano na AdBlocku a na AdBlocku Plus.
Upravil jsem pravidla podle mych poslednich testu.
=> Aktualizace pro novinky.cz

filters.txt
1) `script:inject` filtr zpusobuje, ze filtry pro zive.cz jsou nefunkcni
2) Pridan `div.ads` filtr, ktery funguje na obou domenach
=> Aktualizace pro zive.cz a mobilmania.cz

filters.txt
Toto pravidlo je platne pouze po uBlock, ktery ho ma importovane.
=> Odstraneni neplatneho pravidla

filters.txt
spolehlive zablokuje videoreklamy, napriklad zde
https://technet.idnes.cz/foto.aspx?r=vojenstvi&c=A180918_120637_vojenstvi_kuz&foto=V180904_160405_technet_vrja
=> zablokovani videoreklam na idnes

filters.txt
Odstráni reklamy ktoré pochádzajú z partnerského systému Martinusu
=> Added rule for partner.mrtns.eu

filters.txt
The gemius.pl rule should not be included in this filter list, because it is not serving ads but tracking scripts. That being said, tracking scripts should be reported to and included in the EasyPrivacy filter list.
=> Gemius.pl removal

filters.txt
Obcas se jeste po prave strane objevoval ctverec a obdelnik s reklamou. Tohle pravidlo je zrusi.
=> Centrum.cz: Jeste jeden druh reklam

filters.txt
Filter `||bombuj.eu/*.php$subdocument` v [internom uBlock filtri](https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt) blokuje aj stránky bez ktorých sa nenačíta prehrávanie na bombuj.eu. Tento PR pridáva výnimky pre tieto stránky.
=> Výnimky pre bombuj.eu

filters.txt
Exponea service is used for tracking users, creating profiles and gathering all available personal and behavior information for creating personalized offers. Domain exponea.com is blocked by main easylist filter, but this service also offers implementation on custom domains. One of them is api-exponea.o2.sk used on multiple sites of O2 SK and CZ (for example o2.sk, o2vyhody.cz).
=> Block custom Exponea implementation on o2.sk

filters.txt
Domain api-exponea.o2.cz has the same tracking purpose as an axisting api-exponea.o2.sk
=> Block custom Exponea implementation on o2.cz

filters.txt
Fixes #319. The issue is that the actual class used on the site contains `\x0d\x0b` instead of the ascii `a`. Not sure if it's a typo or if it was intentional, but it was a fun bug to investigate.
=> Fix class selector for krimi-plzen.cz

filters_ublock.txt
Website zdopravy.cz introduced obtrusive ad blocker detection which hides the whole article until a button is clicked. I don't think this can be solved without a scriptlet.
=> Circumvent ad blocker detection on zdopravy.cz

filters.txt
Pridaný 3rd-party filter pre blokovanie reklám z web2media - ako napríklad na stránke bbonline.sk
=> Blokovanie reklám z web2media

filters.txt
I don't know if krimi-plzen.cz changed their classes again or what happened, but I remember they used different utf8 characters for their classes, so for example
`.sidebar-partner-box-top` if you write it by hand is just ascii chars, but what's on their website is `b'.sidebar-partn\xd0\xb5r-b\xce\xbfx-top'` (called `encode('utf8')` in Python). So the `e` and `o` are not ascii and therefore the current filter won't work.
The only way to make this work is to copy paste the exact class from source and use that until they change it again, unfortunately.
=> Fix partner class for krimi-plzen.cz

filters.txt
Hi, @tomasko126, I am absolutely sorry but there seems to be a change in the way the content is displaed at `https://www.seznam.cz/` and this filter supposed to hide the side banner is crushing the page styling. Could you please remove it, we are looking into finding another ways of getting rid of that ad, without breaking the style. Thank a lot.
=> D: `seznam.cz##div[style*="max-height:"]`

filters.txt
This removes the parent element which was just blank space. Luckily, the site uses generic yet specific class names for ads.
=> Improve "vranovske.sk" filter

.gitattributes
This PR adds
- syntax highlight for https://github.com/tomasko126/easylistczechandslovak/blob/master/filters_ublock.txt
- "Adblock Filter List" to the repo statistics:
- *Note*: It seems that the [`.tpl` file](https://github.com/tomasko126/easylistczechandslovak/blob/master/filters_ie.tpl) is detected as Smarty in the stats. Is this file really still needed? It hasn't been updated in 6 years and IE is also dead.
You can find more information about adblock syntax highlighting at the following link: https://github.com/AdguardTeam/VscodeAdblockSyntax#features
=> Configure GitHub Linguist

filters.txt
Zablokuje video reklamy na stranke garaz.tv a na inych strankach ktore vyuzivaju tivio
=> Blokovanie video reklam z tivio

filters.txt
Some parts of the site will disappear when adblock is detected, as explained here: https://www.eduself.sk/blokovanie-obsahu
This removes the script which handles and detects adblock.
=> Block prebid-ads on eduself.sk

filters.txt
Odstráni reklamy z ticketportalu ... aktuálne sú napr. na webe brainee.sk
=> Remove ticketportal carousels ads

filters.txt
Bypass adblock detection.
URL: https://tn.nova.cz/auto/clanek/529608-sileny-rekord-tenhle-ridic-by-vam-nejspis-projel-i-dvermi-od-bytu
=> tn.nova.cz adblock detection bypass

filters_ublock.txt
If these are blocked, you will get "Pravděpodobně používáte rozšíření či blokátory, jež mohou ovlivňovat načtení této stránky. Pro správnou funkčnost prosíme, deaktivujte všechna tato rozšíření a zkuste stránku načíst znovu." message, so I added this filter to prevent that. "Dan Pollock’s hosts file" for example has that domain, so if you have that filterlist enabled, it would totaly breaks the website, but with these filters it works again.
Also "AdGuard – Cookie Notices" filterlist broke the website too, so I added fix for that too (but they apparently already fixed it, but I´m going to keep this fix here just for case :) )
=> Seznam.cz "blocker" detection prevention

filters.txt
Prosím o pridanie nášho scriptu,  ktorý je momentálne blokovaný aj napriek tomu, že jeho funkčnosť nesúvisí s reklamou, alebo zhromažďovaním osobných údajov, do whitelistu.
Tento script je navrhnutý výhradne na pomoc eshopom, ktoré ponúkajú svoje produkty na zrovnávači cien [Heureka.cz](http://heureka.cz/) a [Heureka.sk](http://heureka.sk/). Úlohou scriptu je zobraziť počet objednávok, ktoré boli na eshope vykonané pomocou Heureky. Neobsahuje žiadne reklamné prvky a k fungovaniu nezhromažďuje dáta ani žiadne osobné údaje užívateľov. Skript zároveň berie do úvahy consent vyjadrený používateľom. Jeho jediným účelom je poskytovať eshopom dôležité štatistické údaje o výkonnosti ich predaja.
Blokovanie tohto scriptu má priamy negatívny dopad na presnosť štatistík eshopov, keďže nezaznamenané …
=> Whitelist heureka konverzného skriptu

filters.txt
test url:
https://www.eduself.sk/slovensky-jazyk/tvary-slova/abakus
adds whitelist to:
https://ads.eduself.sk/_prebid.js?hash=skdjh
containing:
```js
var e=document.createElement('div');
e.id='ZwGYbAoajgQE';
e.style.display='none';
ab=false;
document.body.appendChild(e);
```
defuses:
```js
<script>
if (!document.getElementById('ZwGYbAoajgQE'))
ab = true;
</script>
```
alternative filter:
`www.eduself.sk##+js(set, ab, false)`
=> Bypass adblock detection at eduself.sk

filters.txt
This pull request adds a simple element hiding rule that hides the top ad on the homepage of the website `telekomunikace.cz`
Added filter:
```
telekomunikace.cz##.Flagrow-Ads-under-header
```
Closes #435.
=> add telekomunikace.cz

filters.txt, filters_ublock.txt
This pull request fixes anti-adblock filters for `titulky.com` website. Fixes #446
added filters:
```
@@||www.titulky.com/ads/titulky-ads-bottom.js
titulky.com###head_c:style(margin-top: 0 !important;)
```
`/ads/titulky-ads-bottom.js`:
```js
var showBanner600=true;
var showBanner700=true;
var showBanner735=true;
var showFairUser=true;
bannerSkyscraperHeight='600px';
verTimer=2.01;
console.log("Titulky.com verTimer: " + verTimer);
```
`/Ludwig-nejnovejsi-406670.htm`:
```js
if(typeof showFairUser !== 'undefined' && showFairUser){
console.log("Good user!");
var adbUser=false;
}else{
showFairUser=false;
console.log("Poor user!");	
var adbUser=true;
}
```
`/Ludwig-nejnovejsi-406670.htm`:
```js
<script>
$(".titulkydownloadajax").each(function() {
...
adbUser && $(this).parent().html('<div …
```
=> fix titulky.com

filters.txt, filters_ublock.txt
This pull request fixes anti-adblock filters for `titulky.com` website (again). The same detection and testing method as described in #447, just the url was changed from `/ads/titulky-ads-bottom.js` to `/ads/titulky-ads-banner.js`
changed filters:
```diff
- @@||titulky.com/ads/titulky-ads-bottom.js
+ @@||titulky.com/ads/titulky-ads-banner.js
```
you should see `Good user!` printed in the console
- chrome + manifest v2 ublock origin
- enabled filter lists:
- ublock built-in / all
- ads / easylist (required to block top ad)
- privacy / easyprivacy (required to block sidebar ad)
=> fix titulky.com v2

filters.txt, filters_ublock.txt
The site owner updated most of his anti-adblock detection 3 hours ago with some changes 2 hours ago, so more fixes had do be done. Now the filters are more generic. I also removed obsolete filters and updated filter to hide footer ads. 
Note that the site randomly chooses between 3-rd party and 1-st party ads in the 300x300 spot. You may need more refreshes to get the 1-st party ad
- chrome + manifest v2 ublock origin
- enabled filter lists:
- ublock built-in / all
- ads / easylist
- privacy / easyprivacy
=> fix titulky.com v4

filters.txt
This pull request fixes compatibility with adblock plus
It looks like adblock plus needs additional `genericblock` whitelisting rule to ignore generic network rules. Ublock origin will happily ignore that rule, because that behaviour it already a part of  `generichide`.
- adblock plus mv2 chrome
- ublock origin mv2 chrome
- brave
=> titulky.com abp compatibility

filters.txt, filters_ublock.txt
We are still bypassing with ublock origin, this pull request fixes adblock plus. Also addresses incorrect bait url mentioned in [uBlockOrigin/uAssets/issues/26685](https://github.com/uBlockOrigin/uAssets/issues/26685#issuecomment-2567095486) and prevent's leaking adblock use to the server side (ublock origin only)
=> fix titulky.com v7

filters.txt, filters_ublock.txt
Fixed filters for the footer ads
Note: The site renders differently based on the source ip. The numeric part of `#martevax` is a random number, seeded by source ip
=> fix titulky.com v11

filters.txt
Fixes first party ads filters on e-mostecko.cz. The filters are more specific to not block "Sledujte nás na Instagramu" part of the page
Homepage:
blocks wide banners + sidebar banner
Article page:
blocks bottom wide banner
=> fix e-mostecko.cz

filters.txt
`motoforum.cz##img[alt="Reklama"]` blocks aside first party ad (on the right side of the page). This filter also blocks other first party ads on the page, but `motoforum.cz##.advert` filter is better for that, because it also cleans up the `Promo` box around the ads. Also removed old filter
=> fix motoforum.cz

filters.txt
Removes multiple ad spots, some on homepage, some in the article view.
Note: the site used non-ascii `ｅ` to bypass previous filter  (`partnｅr`)
Also removed unused filters
=> fix krimi-plzen.cz

filters.txt
This filter adds ban.tipsport.cz - serving only banners as a third-party. There is already a similar filter `||ban.tipsport.sk^$third-party`, this one is the same for the czech domain.
Example of a site, where these banners are served: https://www.onlajny.com/ (see background ad on the desktop)
=> add ban.tipsport.cz

filters.txt
Additional filter to hide background alza ad (desktop only). Old filters are up-to-date.
=> fix programujte.com

filters.txt
Hides fastshare ads on warcenter.cz:
- `warcenter.cz##td[bgcolor="#066490"]` - blocks banner ad on the top of the page
- `warcenter.cz/interstitial_fs.js` blocks modal ad - note: it shows only on the first load, clear cookies to see it again
interstitial.js is a generic ad script for fastshare ads, we already block it on sktorrent.eu site
=> add warcenter.cz

filters.txt
fastshare.cz has another domain, which serves third-party ads - fastshare.cloud
Example of a site, where ads are served from fastshare.cloud: warforum.xyz
=> add fastshare.cloud

filters.txt
Hides sns ad on top of the homepage
warning - disinformation website according to https://konspiratori.sk/zoznam-stranok
=> add hlavnydennik.sk

filters.txt
Hides ad at the top of the page. Also removed old filter (pretaktovanie.zoznam.sk redirects to pretaktovanie.sk)
=> fix pretaktovanie.sk

filters.txt, filters_ublock.txt
Hides all ads by blocking seznam.cz ad script. We can't block seznam.cz entirely, because the site forces cookie consent throught seznam.cz.
Also removed old filter
=> fix horoskopy.cz

filters.txt
The site didn't update their code, I just made a mistake in #477. We have to whitelist one more url, because our 1st party filter `||cdn.cpex.cz^` blocks it. The site doesn't show ads even with this url whitelisted with default ublock filters + our filterlist.
Testing procedure is unchanged #477 -  check if 24 hour / 3 days / 7 days suggestions are loaded in any [article page](https://hnonline.sk/finweb/ekonomika/96189221)
=> fix hnonline.sk v2

filters.txt
I have returned `.rklm` whitelist filter for `parabola.cz` back after removing in #469, since the article contents won't load without it.
=> Fix parabola.cz articles

filters.txt
The site doesn't really need javascript, so I blocked all in the `/js/` folder, which includes ads too. The forced GDPR "consent" still works (clear cookies to see it)
=> fix horoskopy.cz v2
